export { default as ICVercel } from './vercel.svg'
export { default as ICSend } from './Send.svg'
export { default as ICBimaUtama } from './bima-utama.svg'
export { default as ICDashboard } from './ICDashboard.svg'
export { default as ICResearch } from './ICResearch.svg'
export { default as ICAbimas } from './ICAbimas.svg'
export { default as ICPublications } from './ICPublications.svg'

// Landing
export { default as ICBrieftCase } from './ICBrieftCase.svg'
export { default as ICTrello } from './ICTrello.svg'
export { default as ICSend2 } from './ICSend.svg'
export { default as ICGift } from './ICGift.svg'
export { default as ICWifiOff } from './ICWifiOff.svg'
export { default as ICGlobe } from './ICGlobe.svg'
