export { default as ILLoginBgBottom } from './login-bg-bottom.svg'
export { default as ILLandingBgHeader } from './landing-bg-header.svg'
export { default as ILLandingBgBottom } from './landing-bg-bottom.svg'
export { default as ILSampleArticleCover } from './sample-article-cover.png'
export { default as ILSampleAvatar } from './sample-avatar.png'
